name: iOS-IPA-Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      # Update Podfile to set iOS version to 13.0
      - name: Update Podfile iOS version
        run: |
          sed -i '' 's/platform :ios, .*$/platform :ios, '\''13.0'\''/' ios/Podfile
          sed -i '' 's/# platform :ios, '\''.*'\''/platform :ios, '\''13.0'\''/' ios/Podfile

      - run: pod repo update
        working-directory: ios

      - run: pod install
        working-directory: ios


      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.1
          overwrite: true
          body: "This is first release"